language: cpp
compiler:
  - gcc
  - clang
script: sudo apt-get update -qq && sudo apt-get install -qq wine && export PATH=$PATH:./ucpp-master/ucpp && ucpp setup -t 1334 && ucpp init && ucpp configure py && make