language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
env:
  - PATH=$PATH:./ucpp-master/ucpp
script: ucpp setup -t 1334 && ucpp init && ucpp configure py && make