language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
  - curl -L -o ./master.zip  https://github.com/nikitakit/ucpp/archive/master.zip
  - unzip -o ./master.zip
env:
  - PATH=$PATH:./ucpp-master/ucpp
script: ucpp setup -t 1334 && ucpp init && ucpp configure py && make
